anumsaeed@DESKTOP-M2SFVT4:~$ sudo rm /etc/apt/sources.list.d/mssql-release.list
anumsaeed@DESKTOP-M2SFVT4:~$ curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--100    89  100    89    0     0     46      0  0:00:01  0:00:01 --:--:--100    89  100    89    0     0     46      0  0:00:01  0:00:01 --:--:--    46
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
anumsaeed@DESKTOP-M2SFVT4:~$ sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
Hit:1 http://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [77.4 kB]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [1331 B]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [244 kB]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [20.9 kB]
Fetched 347 kB in 4s (86.6 kB/s)
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libodbc2 libodbccr2 unixodbc
Suggested packages:
  odbc-postgresql tdsodbc
The following NEW packages will be installed:
  libodbc2 libodbccr2 msodbcsql17 unixodbc unixodbc-dev
0 upgraded, 5 newly installed, 0 to remove and 132 not upgraded.
Need to get 1198 kB of archives.
After this operation, 2466 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libodbc2 amd64 2.3.12-1ubuntu0.24.04.1 [158 kB]
Get:2 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 msodbcsql17 amd64 17.10.6.1-1 [746 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libodbccr2 amd64 2.3.12-1ubuntu0.24.04.1 [16.1 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 unixodbc amd64 2.3.12-1ubuntu0.24.04.1 [27.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 unixodbc-dev amd64 2.3.12-1ubuntu0.24.04.1 [250 kB]
Fetched 1198 kB in 3s (398 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libodbc2:amd64.
(Reading database ... 48831 files and directories currently installed.)
Preparing to unpack .../libodbc2_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libodbc2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package libodbccr2:amd64.
Preparing to unpack .../libodbccr2_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libodbccr2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package unixodbc.
Preparing to unpack .../unixodbc_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking unixodbc (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package msodbcsql17.
Preparing to unpack .../msodbcsql17_17.10.6.1-1_amd64.deb ...
Unpacking msodbcsql17 (17.10.6.1-1) ...
Selecting previously unselected package unixodbc-dev:amd64.
Preparing to unpack .../unixodbc-dev_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking unixodbc-dev:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up libodbc2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up libodbccr2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up unixodbc (2.3.12-1ubuntu0.24.04.1) ...
Setting up msodbcsql17 (17.10.6.1-1) ...
odbcinst: Driver installed. Usage count increased to 1.
    Target directory is /etc
Setting up unixodbc-dev:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.5) ...
anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
[ODBC Driver 17 for SQL Server]
anumsaeed@DESKTOP-M2SFVT4:~$ cd /mnt/c/Users/ADMIN/deepframe-backend
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services$ cd image_grouping
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose build

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/

anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker --version
Docker version 28.3.2, build 578ccf6
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose build
[+] Building 0.0s (0/0)
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose build
[+] Building 325.6s (11/22)
 => [internal] load local bake definitions                                                                                                     0.0s
 => => reading from stdin 461B                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 2.07kB                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.8.20                                                                               4.4s
 => [internal] load .dockerignore                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                0.0s
 => [ 1/17] FROM docker.io/library/python:3.8.20@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c                       0.0s
 => => resolve docker.io/library/python:3.8.20@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c                         0.0s
 => [internal] load build context                                                                                                              0.4s
 => => transferring context: 6.31MB                                                                                                            0.3s
 => CACHED [ 2/17] RUN apt-get update &&     apt-get install -y curl gnupg &&     curl https://packages.microsoft.com/keys/microsoft.asc | ap  0.0s
 => CACHED [ 3/17] RUN apt-get update && apt-get install -y     unixodbc     unixodbc-dev     libodbc1     libgl1-mesa-glx     libglib2.0-0    0.0s
 => CACHED [ 4/17] RUN if ! command -v tini >/dev/null 2>&1; then         apt-get update && apt-get install -y tini && rm -rf /var/lib/apt/li  0.0s
 => CACHED [ 5/17] WORKDIR /app/services/image_grouping                                                                                        0.0s
 => [ 6/17] COPY docker/requirements.txt ./requirements.txt                                                                                    0.0s
 => [ 7/17] RUN pip install --no-cache-dir --upgrade -r requirements.txt                                                                     320.5s
 => => #      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 1.0 MB/s eta 0:00:00
 => => # Collecting matplotlib
 => => #   Downloading matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
 => => #      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 764.8 kB/s eta 0:00:00
 => => # Collecting tensorflow
 => => #   Downloading tensorflow-2.13.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (479.6 MB)

 root@02f53b74fb26:/app/services/image_grouping# odbcinst -q -d
[ODBC Driver 17 for SQL Server]
root@02f53b74fb26:/app/services/image_grouping#

anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
odbcinst: SQLGetPrivateProfileString failed with .
anumsaeed@DESKTOP-M2SFVT4:~$ sudo -i
[sudo] password for anumsaeed:
root@DESKTOP-M2SFVT4:~# curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--100   975  100   975    0     0    525      0  0:00:01  0:00:01 --:--:--   525
OK
root@DESKTOP-M2SFVT4:~# curl https://packages.microsoft.com/config/ubuntu/24.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--100   138  100   138    0     0     75      0  0:00:01  0:00:01 --:--:--    75
root@DESKTOP-M2SFVT4:~# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Get:2 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:3 http://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease [107 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:5 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease [3600 B]
Err:5 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Get:6 http://apt.postgresql.org/pub/repos/apt noble-pgdg/main amd64 Packages [336 kB]
Get:7 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [1106 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1379 kB]
Get:10 http://security.ubuntu.com/ubuntu noble-security/main Translation-en [190 kB]
Get:11 http://security.ubuntu.com/ubuntu noble-security/main amd64 Components [21.6 kB]
Get:12 http://security.ubuntu.com/ubuntu noble-security/main amd64 c-n-f Metadata [8708 B]
Get:13 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [881 kB]
Get:14 http://security.ubuntu.com/ubuntu noble-security/universe Translation-en [195 kB]
Get:15 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Components [52.2 kB]
Get:16 http://security.ubuntu.com/ubuntu noble-security/universe amd64 c-n-f Metadata [18.0 kB]
Get:17 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [1685 kB]
Get:18 http://security.ubuntu.com/ubuntu noble-security/restricted Translation-en [377 kB]
Get:19 http://archive.ubuntu.com/ubuntu noble-updates/main Translation-en [272 kB]
Get:20 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Components [212 B]
Get:21 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Components [208 B]
Get:22 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Components [175 kB]
Get:23 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 c-n-f Metadata [14.9 kB]
Get:24 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [1471 kB]
Get:25 http://archive.ubuntu.com/ubuntu noble-updates/universe Translation-en [297 kB]
Get:26 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Components [377 kB]
Get:27 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 c-n-f Metadata [30.5 kB]
Get:28 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [1785 kB]
Get:29 http://archive.ubuntu.com/ubuntu noble-updates/restricted Translation-en [399 kB]
Get:30 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Components [212 B]
Get:31 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Components [940 B]
Get:32 http://archive.ubuntu.com/ubuntu noble-backports/main amd64 Components [7076 B]
Get:33 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [30.2 kB]
Get:34 http://archive.ubuntu.com/ubuntu noble-backports/universe Translation-en [17.4 kB]
Get:35 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Components [19.2 kB]
Get:36 http://archive.ubuntu.com/ubuntu noble-backports/restricted amd64 Components [216 B]
Get:37 http://archive.ubuntu.com/ubuntu noble-backports/multiverse amd64 Components [212 B]
Reading package lists... Done
W: GPG error: https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@DESKTOP-M2SFVT4:~# ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package msodbcsql17
root@DESKTOP-M2SFVT4:~# exit
logout
anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
odbcinst: SQLGetPrivateProfileString failed with .
anumsaeed@DESKTOP-M2SFVT4:~$ sudo rm /etc/apt/sources.list.d/mssql-release.list
anumsaeed@DESKTOP-M2SFVT4:~$ curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--100    89  100    89    0     0     46      0  0:00:01  0:00:01 --:--:--100    89  100    89    0     0     46      0  0:00:01  0:00:01 --:--:--    46
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
anumsaeed@DESKTOP-M2SFVT4:~$ sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
Hit:1 http://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [77.4 kB]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [1331 B]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [244 kB]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [20.9 kB]
Fetched 347 kB in 4s (86.6 kB/s)
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libodbc2 libodbccr2 unixodbc
Suggested packages:
  odbc-postgresql tdsodbc
The following NEW packages will be installed:
  libodbc2 libodbccr2 msodbcsql17 unixodbc unixodbc-dev
0 upgraded, 5 newly installed, 0 to remove and 132 not upgraded.
Need to get 1198 kB of archives.
After this operation, 2466 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libodbc2 amd64 2.3.12-1ubuntu0.24.04.1 [158 kB]
Get:2 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 msodbcsql17 amd64 17.10.6.1-1 [746 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libodbccr2 amd64 2.3.12-1ubuntu0.24.04.1 [16.1 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 unixodbc amd64 2.3.12-1ubuntu0.24.04.1 [27.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 unixodbc-dev amd64 2.3.12-1ubuntu0.24.04.1 [250 kB]
Fetched 1198 kB in 3s (398 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libodbc2:amd64.
(Reading database ... 48831 files and directories currently installed.)
Preparing to unpack .../libodbc2_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libodbc2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package libodbccr2:amd64.
Preparing to unpack .../libodbccr2_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libodbccr2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package unixodbc.
Preparing to unpack .../unixodbc_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking unixodbc (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package msodbcsql17.
Preparing to unpack .../msodbcsql17_17.10.6.1-1_amd64.deb ...
Unpacking msodbcsql17 (17.10.6.1-1) ...
Selecting previously unselected package unixodbc-dev:amd64.
Preparing to unpack .../unixodbc-dev_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking unixodbc-dev:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up libodbc2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up libodbccr2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up unixodbc (2.3.12-1ubuntu0.24.04.1) ...
Setting up msodbcsql17 (17.10.6.1-1) ...
odbcinst: Driver installed. Usage count increased to 1.
    Target directory is /etc
Setting up unixodbc-dev:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.5) ...
anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
[ODBC Driver 17 for SQL Server]
anumsaeed@DESKTOP-M2SFVT4:~$ cd /mnt/c/Users/ADMIN/deepframe-backend
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services$ cd image_grouping
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose build

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/

anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker --version
Docker version 28.3.2, build 578ccf6
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose build
[+] Building 0.0s (0/0)
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose build
[+] Building 1813.8s (24/24) FINISHED
 => [internal] load local bake definitions                                                                                                     0.0s
 => => reading from stdin 461B                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 2.07kB                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.8.20                                                                               4.4s
 => [internal] load .dockerignore                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                0.0s
 => [ 1/17] FROM docker.io/library/python:3.8.20@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c                       0.0s
 => => resolve docker.io/library/python:3.8.20@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c                         0.0s
 => [internal] load build context                                                                                                              0.4s
 => => transferring context: 6.31MB                                                                                                            0.3s
 => CACHED [ 2/17] RUN apt-get update &&     apt-get install -y curl gnupg &&     curl https://packages.microsoft.com/keys/microsoft.asc | ap  0.0s
 => CACHED [ 3/17] RUN apt-get update && apt-get install -y     unixodbc     unixodbc-dev     libodbc1     libgl1-mesa-glx     libglib2.0-0    0.0s
 => CACHED [ 4/17] RUN if ! command -v tini >/dev/null 2>&1; then         apt-get update && apt-get install -y tini && rm -rf /var/lib/apt/li  0.0s
 => CACHED [ 5/17] WORKDIR /app/services/image_grouping                                                                                        0.0s
 => [ 6/17] COPY docker/requirements.txt ./requirements.txt                                                                                    0.0s
 => [ 7/17] RUN pip install --no-cache-dir --upgrade -r requirements.txt                                                                    1749.5s
 => [ 8/17] COPY person_recognition/ ./person_recognition/                                                                                     0.3s
 => [ 9/17] COPY image_face_detection/ ./image_face_detection/                                                                                 0.1s
 => [10/17] COPY main.py ./main.py                                                                                                             0.1s
 => [11/17] COPY docker/docker-entrypoint.sh /usr/local/bin/                                                                                   0.0s
 => [12/17] COPY docker/healthcheck.py ./docker/healthcheck.py                                                                                 0.1s
 => [13/17] COPY config.py ./config.py                                                                                                         0.1s
 => [14/17] COPY .env ./.env                                                                                                                   0.1s
 => [15/17] COPY person_recognition/logger_config.py ./person_recognition/logger_config.py                                                     0.1s
 => [16/17] COPY image_face_detection/logger_config.py ./image_face_detection/logger_config.py                                                 0.1s
 => [17/17] RUN chmod +x /usr/local/bin/docker-entrypoint.sh     && mkdir -p person_recognition/logs image_face_detection/logs                 0.3s
 => exporting to image                                                                                                                        58.0s
 => => exporting layers                                                                                                                       46.7s
 => => exporting manifest sha256:1e91f602dad4d118c1e7a13c9e38543dde135a316205564ddf0dbe8518459494                                              0.0s
 => => exporting config sha256:d9b14bbec8d43be54af7da7795332df634f27e6dcb8079a113c02809cbf47917                                                0.0s
 => => exporting attestation manifest sha256:f191ad0c86acc812a0b95bbf3eb6497599fb6d4991daa61297158aabfd5cb552                                  0.0s
 => => exporting manifest list sha256:7f6b77481ae4a53df43e96c3627d635509eac5be7eea17f6b1566a79d302045b                                         0.0s
 => => naming to docker.io/library/image_grouping-image_grouping:latest                                                                        0.0s
 => => unpacking to docker.io/library/image_grouping-image_grouping:latest                                                                    11.2s
 => resolving provenance for metadata file                                                                                                     0.0s
[+] Building 1/1
 ✔ image_grouping  Built                                                                                                                       0.0s
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose up
unable to get image 'image_grouping-image_grouping': permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/images/image_grouping-image_grouping/json": dial unix /var/run/docker.sock: connect: permission denied
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose up
[sudo] password for anumsaeed:
[+] Running 1/1
 ✔ Container image-grouping-service  Recreated                                                                                                 1.8s
Attaching to image-grouping-service
image-grouping-service  | + export DB_HOST=sqlserver
image-grouping-service  | + DB_HOST=sqlserver
image-grouping-service  | + export DB_PORT=1433
image-grouping-service  | + DB_PORT=1433
image-grouping-service  | + export DB_USER=sa
image-grouping-service  | + DB_USER=sa
image-grouping-service  | + export DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + export DB_NAME=MediaDB
image-grouping-service  | + DB_NAME=MediaDB
image-grouping-service  | + SERVICE=recognition
image-grouping-service  | + MODE=oneshot
image-grouping-service  | + INTERVAL_SECONDS=900
image-grouping-service  | + RECOGNIZER_ARGS=--recluster
image-grouping-service  | + mkdir -p person_recognition/logs image_face_detection/logs
image-grouping-service  | + '[' oneshot = loop ']'
image-grouping-service  | + run_service
image-grouping-service  | + case $SERVICE in
image-grouping-service  | + LOGFILE=person_recognition/logs/run.log
image-grouping-service  | ++ date
image-grouping-service  | + echo '[Mon Sep  1 09:44:09 UTC 2025] Running recognition with args: --recluster'
image-grouping-service  | + python main.py --recluster
image-grouping-service  | 2025-09-01 09:44:09.810173: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:44:09.841261: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:44:10.063748: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:44:10.064879: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:44:10.787497: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT






Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container image-grouping-service  Stopped                                                                                                   8.8s
^C
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker exec -it image-grouping-service bash
Error response from daemon: container 02f53b74fb2625566f0808551faa861045381f9ce60dc2cbdae1e501eb662d03 is not running
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose up
Attaching to image-grouping-service
image-grouping-service  | + export DB_HOST=sqlserver
image-grouping-service  | + DB_HOST=sqlserver
image-grouping-service  | + export DB_PORT=1433
image-grouping-service  | + DB_PORT=1433
image-grouping-service  | + export DB_USER=sa
image-grouping-service  | + DB_USER=sa
image-grouping-service  | + export DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + export DB_NAME=MediaDB
image-grouping-service  | + DB_NAME=MediaDB
image-grouping-service  | + SERVICE=recognition
image-grouping-service  | + MODE=oneshot
image-grouping-service  | + INTERVAL_SECONDS=900
image-grouping-service  | + RECOGNIZER_ARGS=--recluster
image-grouping-service  | + mkdir -p person_recognition/logs image_face_detection/logs
image-grouping-service  | + '[' oneshot = loop ']'
image-grouping-service  | + run_service
image-grouping-service  | + case $SERVICE in
image-grouping-service  | + LOGFILE=person_recognition/logs/run.log
image-grouping-service  | ++ date
image-grouping-service  | + echo '[Mon Sep  1 09:45:59 UTC 2025] Running recognition with args: --recluster'
image-grouping-service  | + python main.py --recluster
image-grouping-service  | 2025-09-01 09:45:59.421163: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:45:59.422466: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:45:59.445359: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:45:59.445693: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:46:00.088558: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT




















image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:46:20] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:46:51.340139: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:46:51.341494: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:46:51.364828: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:46:51.365190: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:46:52.010879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose up
Attaching to image-grouping-service
image-grouping-service  | + export DB_HOST=sqlserver
image-grouping-service  | + DB_HOST=sqlserver
image-grouping-service  | + export DB_PORT=1433
image-grouping-service  | + DB_PORT=1433
image-grouping-service  | + export DB_USER=sa
image-grouping-service  | + DB_USER=sa
image-grouping-service  | + export DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + export DB_NAME=MediaDB
image-grouping-service  | + DB_NAME=MediaDB
image-grouping-service  | + SERVICE=recognition
image-grouping-service  | + MODE=oneshot
image-grouping-service  | + INTERVAL_SECONDS=900
image-grouping-service  | + RECOGNIZER_ARGS=--recluster
image-grouping-service  | + mkdir -p person_recognition/logs image_face_detection/logs
image-grouping-service  | + '[' oneshot = loop ']'
image-grouping-service  | + run_service
image-grouping-service  | + case $SERVICE in
image-grouping-service  | + LOGFILE=person_recognition/logs/run.log
image-grouping-service  | ++ date
image-grouping-service  | + echo '[Mon Sep  1 09:45:59 UTC 2025] Running recognition with args: --recluster'
image-grouping-service  | + python main.py --recluster
image-grouping-service  | 2025-09-01 09:45:59.421163: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:45:59.422466: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:45:59.445359: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:45:59.445693: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:46:00.088558: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT




















image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:46:20] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:46:51.340139: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:46:51.341494: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:46:51.364828: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:46:51.365190: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:46:52.010879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:47:12] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:47:43.355992: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:47:43.357403: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:47:43.380951: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:47:43.381304: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:47:44.006357: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


v View in














anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
odbcinst: SQLGetPrivateProfileString failed with .
anumsaeed@DESKTOP-M2SFVT4:~$ sudo -i
[sudo] password for anumsaeed:
root@DESKTOP-M2SFVT4:~# curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--100   975  100   975    0     0    525      0  0:00:01  0:00:01 --:--:--   525
OK
root@DESKTOP-M2SFVT4:~# curl https://packages.microsoft.com/config/ubuntu/24.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--100   138  100   138    0     0     75      0  0:00:01  0:00:01 --:--:--    75
root@DESKTOP-M2SFVT4:~# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Get:2 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:3 http://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease [107 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:5 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease [3600 B]
Err:5 https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
Get:6 http://apt.postgresql.org/pub/repos/apt noble-pgdg/main amd64 Packages [336 kB]
Get:7 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [1106 kB]
Get:8 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1379 kB]
Get:10 http://security.ubuntu.com/ubuntu noble-security/main Translation-en [190 kB]
Get:11 http://security.ubuntu.com/ubuntu noble-security/main amd64 Components [21.6 kB]
Get:12 http://security.ubuntu.com/ubuntu noble-security/main amd64 c-n-f Metadata [8708 B]
Get:13 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [881 kB]
Get:14 http://security.ubuntu.com/ubuntu noble-security/universe Translation-en [195 kB]
Get:15 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Components [52.2 kB]
Get:16 http://security.ubuntu.com/ubuntu noble-security/universe amd64 c-n-f Metadata [18.0 kB]
Get:17 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [1685 kB]
Get:18 http://security.ubuntu.com/ubuntu noble-security/restricted Translation-en [377 kB]
Get:19 http://archive.ubuntu.com/ubuntu noble-updates/main Translation-en [272 kB]
Get:20 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Components [212 B]
Get:21 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Components [208 B]
Get:22 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Components [175 kB]
Get:23 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 c-n-f Metadata [14.9 kB]
Get:24 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [1471 kB]
Get:25 http://archive.ubuntu.com/ubuntu noble-updates/universe Translation-en [297 kB]
Get:26 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Components [377 kB]
Get:27 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 c-n-f Metadata [30.5 kB]
Get:28 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [1785 kB]
Get:29 http://archive.ubuntu.com/ubuntu noble-updates/restricted Translation-en [399 kB]
Get:30 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Components [212 B]
Get:31 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Components [940 B]
Get:32 http://archive.ubuntu.com/ubuntu noble-backports/main amd64 Components [7076 B]
Get:33 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [30.2 kB]
Get:34 http://archive.ubuntu.com/ubuntu noble-backports/universe Translation-en [17.4 kB]
Get:35 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Components [19.2 kB]
Get:36 http://archive.ubuntu.com/ubuntu noble-backports/restricted amd64 Components [216 B]
Get:37 http://archive.ubuntu.com/ubuntu noble-backports/multiverse amd64 Components [212 B]
Reading package lists... Done
W: GPG error: https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/ubuntu/24.04/prod noble InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@DESKTOP-M2SFVT4:~# ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package msodbcsql17
root@DESKTOP-M2SFVT4:~# exit
logout
anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
odbcinst: SQLGetPrivateProfileString failed with .
anumsaeed@DESKTOP-M2SFVT4:~$ sudo rm /etc/apt/sources.list.d/mssql-release.list
anumsaeed@DESKTOP-M2SFVT4:~$ curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--100    89  100    89    0     0     46      0  0:00:01  0:00:01 --:--:--100    89  100    89    0     0     46      0  0:00:01  0:00:01 --:--:--    46
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
anumsaeed@DESKTOP-M2SFVT4:~$ sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
Hit:1 http://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [77.4 kB]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [1331 B]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [244 kB]
Get:10 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [20.9 kB]
Fetched 347 kB in 4s (86.6 kB/s)
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libodbc2 libodbccr2 unixodbc
Suggested packages:
  odbc-postgresql tdsodbc
The following NEW packages will be installed:
  libodbc2 libodbccr2 msodbcsql17 unixodbc unixodbc-dev
0 upgraded, 5 newly installed, 0 to remove and 132 not upgraded.
Need to get 1198 kB of archives.
After this operation, 2466 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libodbc2 amd64 2.3.12-1ubuntu0.24.04.1 [158 kB]
Get:2 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 msodbcsql17 amd64 17.10.6.1-1 [746 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libodbccr2 amd64 2.3.12-1ubuntu0.24.04.1 [16.1 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 unixodbc amd64 2.3.12-1ubuntu0.24.04.1 [27.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 unixodbc-dev amd64 2.3.12-1ubuntu0.24.04.1 [250 kB]
Fetched 1198 kB in 3s (398 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libodbc2:amd64.
(Reading database ... 48831 files and directories currently installed.)
Preparing to unpack .../libodbc2_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libodbc2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package libodbccr2:amd64.
Preparing to unpack .../libodbccr2_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking libodbccr2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package unixodbc.
Preparing to unpack .../unixodbc_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking unixodbc (2.3.12-1ubuntu0.24.04.1) ...
Selecting previously unselected package msodbcsql17.
Preparing to unpack .../msodbcsql17_17.10.6.1-1_amd64.deb ...
Unpacking msodbcsql17 (17.10.6.1-1) ...
Selecting previously unselected package unixodbc-dev:amd64.
Preparing to unpack .../unixodbc-dev_2.3.12-1ubuntu0.24.04.1_amd64.deb ...
Unpacking unixodbc-dev:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up libodbc2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up libodbccr2:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Setting up unixodbc (2.3.12-1ubuntu0.24.04.1) ...
Setting up msodbcsql17 (17.10.6.1-1) ...
odbcinst: Driver installed. Usage count increased to 1.
    Target directory is /etc
Setting up unixodbc-dev:amd64 (2.3.12-1ubuntu0.24.04.1) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.5) ...
anumsaeed@DESKTOP-M2SFVT4:~$ odbcinst -q -d
[ODBC Driver 17 for SQL Server]
anumsaeed@DESKTOP-M2SFVT4:~$ cd /mnt/c/Users/ADMIN/deepframe-backend
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services$ cd image_grouping
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose build

The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.

For details about using Docker Desktop with WSL 2, visit:

https://docs.docker.com/go/wsl2/

anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker --version
Docker version 28.3.2, build 578ccf6
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose build
[+] Building 0.0s (0/0)
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose build
[+] Building 1813.8s (24/24) FINISHED
 => [internal] load local bake definitions                                                                                                     0.0s
 => => reading from stdin 461B                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                           0.0s
 => => transferring dockerfile: 2.07kB                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.8.20                                                                               4.4s
 => [internal] load .dockerignore                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                0.0s
 => [ 1/17] FROM docker.io/library/python:3.8.20@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c                       0.0s
 => => resolve docker.io/library/python:3.8.20@sha256:d411270700143fa2683cc8264d9fa5d3279fd3b6afff62ae81ea2f9d070e390c                         0.0s
 => [internal] load build context                                                                                                              0.4s
 => => transferring context: 6.31MB                                                                                                            0.3s
 => CACHED [ 2/17] RUN apt-get update &&     apt-get install -y curl gnupg &&     curl https://packages.microsoft.com/keys/microsoft.asc | ap  0.0s
 => CACHED [ 3/17] RUN apt-get update && apt-get install -y     unixodbc     unixodbc-dev     libodbc1     libgl1-mesa-glx     libglib2.0-0    0.0s
 => CACHED [ 4/17] RUN if ! command -v tini >/dev/null 2>&1; then         apt-get update && apt-get install -y tini && rm -rf /var/lib/apt/li  0.0s
 => CACHED [ 5/17] WORKDIR /app/services/image_grouping                                                                                        0.0s
 => [ 6/17] COPY docker/requirements.txt ./requirements.txt                                                                                    0.0s
 => [ 7/17] RUN pip install --no-cache-dir --upgrade -r requirements.txt                                                                    1749.5s
 => [ 8/17] COPY person_recognition/ ./person_recognition/                                                                                     0.3s
 => [ 9/17] COPY image_face_detection/ ./image_face_detection/                                                                                 0.1s
 => [10/17] COPY main.py ./main.py                                                                                                             0.1s
 => [11/17] COPY docker/docker-entrypoint.sh /usr/local/bin/                                                                                   0.0s
 => [12/17] COPY docker/healthcheck.py ./docker/healthcheck.py                                                                                 0.1s
 => [13/17] COPY config.py ./config.py                                                                                                         0.1s
 => [14/17] COPY .env ./.env                                                                                                                   0.1s
 => [15/17] COPY person_recognition/logger_config.py ./person_recognition/logger_config.py                                                     0.1s
 => [16/17] COPY image_face_detection/logger_config.py ./image_face_detection/logger_config.py                                                 0.1s
 => [17/17] RUN chmod +x /usr/local/bin/docker-entrypoint.sh     && mkdir -p person_recognition/logs image_face_detection/logs                 0.3s
 => exporting to image                                                                                                                        58.0s
 => => exporting layers                                                                                                                       46.7s
 => => exporting manifest sha256:1e91f602dad4d118c1e7a13c9e38543dde135a316205564ddf0dbe8518459494                                              0.0s
 => => exporting config sha256:d9b14bbec8d43be54af7da7795332df634f27e6dcb8079a113c02809cbf47917                                                0.0s
 => => exporting attestation manifest sha256:f191ad0c86acc812a0b95bbf3eb6497599fb6d4991daa61297158aabfd5cb552                                  0.0s
 => => exporting manifest list sha256:7f6b77481ae4a53df43e96c3627d635509eac5be7eea17f6b1566a79d302045b                                         0.0s
 => => naming to docker.io/library/image_grouping-image_grouping:latest                                                                        0.0s
 => => unpacking to docker.io/library/image_grouping-image_grouping:latest                                                                    11.2s
 => resolving provenance for metadata file                                                                                                     0.0s
[+] Building 1/1
 ✔ image_grouping  Built                                                                                                                       0.0s
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ docker compose up
unable to get image 'image_grouping-image_grouping': permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.51/images/image_grouping-image_grouping/json": dial unix /var/run/docker.sock: connect: permission denied
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose up
[sudo] password for anumsaeed:
[+] Running 1/1
 ✔ Container image-grouping-service  Recreated                                                                                                 1.8s
Attaching to image-grouping-service
image-grouping-service  | + export DB_HOST=sqlserver
image-grouping-service  | + DB_HOST=sqlserver
image-grouping-service  | + export DB_PORT=1433
image-grouping-service  | + DB_PORT=1433
image-grouping-service  | + export DB_USER=sa
image-grouping-service  | + DB_USER=sa
image-grouping-service  | + export DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + export DB_NAME=MediaDB
image-grouping-service  | + DB_NAME=MediaDB
image-grouping-service  | + SERVICE=recognition
image-grouping-service  | + MODE=oneshot
image-grouping-service  | + INTERVAL_SECONDS=900
image-grouping-service  | + RECOGNIZER_ARGS=--recluster
image-grouping-service  | + mkdir -p person_recognition/logs image_face_detection/logs
image-grouping-service  | + '[' oneshot = loop ']'
image-grouping-service  | + run_service
image-grouping-service  | + case $SERVICE in
image-grouping-service  | + LOGFILE=person_recognition/logs/run.log
image-grouping-service  | ++ date
image-grouping-service  | + echo '[Mon Sep  1 09:44:09 UTC 2025] Running recognition with args: --recluster'
image-grouping-service  | + python main.py --recluster
image-grouping-service  | 2025-09-01 09:44:09.810173: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:44:09.841261: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:44:10.063748: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:44:10.064879: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:44:10.787497: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT






Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container image-grouping-service  Stopped                                                                                                   8.8s
^C
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker exec -it image-grouping-service bash
Error response from daemon: container 02f53b74fb2625566f0808551faa861045381f9ce60dc2cbdae1e501eb662d03 is not running
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose up
Attaching to image-grouping-service
image-grouping-service  | + export DB_HOST=sqlserver
image-grouping-service  | + DB_HOST=sqlserver
image-grouping-service  | + export DB_PORT=1433
image-grouping-service  | + DB_PORT=1433
image-grouping-service  | + export DB_USER=sa
image-grouping-service  | + DB_USER=sa
image-grouping-service  | + export DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + export DB_NAME=MediaDB
image-grouping-service  | + DB_NAME=MediaDB
image-grouping-service  | + SERVICE=recognition
image-grouping-service  | + MODE=oneshot
image-grouping-service  | + INTERVAL_SECONDS=900
image-grouping-service  | + RECOGNIZER_ARGS=--recluster
image-grouping-service  | + mkdir -p person_recognition/logs image_face_detection/logs
image-grouping-service  | + '[' oneshot = loop ']'
image-grouping-service  | + run_service
image-grouping-service  | + case $SERVICE in
image-grouping-service  | + LOGFILE=person_recognition/logs/run.log
image-grouping-service  | ++ date
image-grouping-service  | + echo '[Mon Sep  1 09:45:59 UTC 2025] Running recognition with args: --recluster'
image-grouping-service  | + python main.py --recluster
image-grouping-service  | 2025-09-01 09:45:59.421163: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:45:59.422466: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:45:59.445359: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:45:59.445693: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:46:00.088558: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT




















image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:46:20] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:46:51.340139: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:46:51.341494: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:46:51.364828: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:46:51.365190: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:46:52.010879: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:47:12] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:47:43.355992: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:47:43.357403: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:47:43.380951: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:47:43.381304: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:47:44.006357: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:48:04] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:48:35.133038: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:48:35.134373: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:48:35.158226: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:48:35.158582: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:48:35.555661: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container image-grouping-service  Stopped                                                                                                   7.2s
^C
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$ sudo docker compose up
Attaching to image-grouping-service
image-grouping-service  | + export DB_HOST=sqlserver
image-grouping-service  | + DB_HOST=sqlserver
image-grouping-service  | + export DB_PORT=1433
image-grouping-service  | + DB_PORT=1433
image-grouping-service  | + export DB_USER=sa
image-grouping-service  | + DB_USER=sa
image-grouping-service  | + export DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + DB_PASSWORD=YourStrong@Passw0rd
image-grouping-service  | + export DB_NAME=MediaDB
image-grouping-service  | + DB_NAME=MediaDB
image-grouping-service  | + SERVICE=recognition
image-grouping-service  | + MODE=oneshot
image-grouping-service  | + INTERVAL_SECONDS=900
image-grouping-service  | + RECOGNIZER_ARGS=--recluster
image-grouping-service  | + mkdir -p person_recognition/logs image_face_detection/logs
image-grouping-service  | + '[' oneshot = loop ']'
image-grouping-service  | + run_service
image-grouping-service  | + case $SERVICE in
image-grouping-service  | + LOGFILE=person_recognition/logs/run.log
image-grouping-service  | ++ date
image-grouping-service  | + echo '[Mon Sep  1 09:49:13 UTC 2025] Running recognition with args: --recluster'
image-grouping-service  | + python main.py --recluster
image-grouping-service  | 2025-09-01 09:49:13.703355: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:49:13.704843: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:49:13.729325: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:49:13.729710: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:49:14.131504: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:49:33] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:50:04.853184: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:50:04.854681: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:50:04.877895: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:50:04.878244: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:50:05.260318: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:50:24] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:50:55.694555: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:50:55.695966: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:50:55.720300: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:50:55.720652: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:50:56.113261: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:51:15] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:51:46.555314: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:51:46.556654: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:51:46.580389: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:51:46.580777: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:51:46.969081: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:52:06] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:52:37.425706: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:52:37.427233: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:52:37.451120: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:52:37.451493: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:52:37.843240: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:52:57] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:53:28.396443: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:53:28.398012: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:53:28.422471: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:53:28.422911: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:53:28.812306: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:53:48] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:54:19.229202: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:54:19.230695: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:54:19.254527: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:54:19.254929: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:54:19.637636: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:54:39] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:55:10.190355: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:55:10.191722: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:55:10.216191: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:55:10.216588: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:55:10.609095: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:55:29] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:56:01.067673: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:56:01.069045: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:56:01.094290: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:56:01.094644: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:56:01.485219: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:56:20] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:56:51.922412: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:56:51.923678: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:56:51.947157: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:56:51.947535: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:56:52.325745: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:57:11] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:57:42.914825: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:57:42.916216: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:57:42.939696: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:57:42.940055: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:57:43.350715: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:58:02] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:58:33.848220: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:58:33.849531: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:58:33.873266: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:58:33.873626: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:58:34.270975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:58:53] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 09:59:24.750490: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 09:59:24.751797: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:59:24.776310: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 09:59:24.776697: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 09:59:25.181946: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 09:59:44] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:00:15.726370: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:00:15.728004: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:00:15.752541: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:00:15.752939: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:00:16.154990: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:00:35] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:01:06.670114: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:01:06.671574: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:01:06.695599: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:01:06.695950: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:01:07.083677: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:01:26] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:01:57.849282: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:01:57.850653: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:01:57.874425: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:01:57.874769: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:01:58.264544: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:02:17] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:02:48.748000: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:02:48.749362: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:02:48.773405: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:02:48.773759: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:02:49.152692: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:03:08] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:03:39.834897: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:03:39.836280: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:03:39.860043: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:03:39.860399: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:03:40.262144: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:03:59] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:04:30.772357: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:04:30.773773: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:04:30.798336: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:04:30.798890: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:04:31.186762: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:04:50] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:05:21.676172: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:05:21.677460: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:05:21.701815: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:05:21.702177: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:05:22.107186: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:05:41] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:06:12.786370: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:06:12.787947: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:06:12.811989: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:06:12.812371: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:06:13.191855: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:06:32] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:07:03.795134: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:07:03.796542: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:07:03.820720: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:07:03.821056: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:07:04.203484: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:07:23] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:07:54.760251: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:07:54.761690: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:07:54.785685: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:07:54.786061: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:07:55.283380: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:08:14] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:08:45.758305: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:08:45.759775: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:08:45.784385: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:08:45.784784: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:08:46.171172: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:09:05] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:09:36.646303: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:09:36.647666: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:09:36.671548: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:09:36.671969: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:09:37.056407: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:09:56] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:10:27.552344: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:10:27.554191: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:10:27.579299: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:10:27.579674: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:10:27.968333: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:10:47] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:11:18.328302: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:11:18.329649: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:11:18.353775: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:11:18.354182: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:11:18.739210: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:11:38] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:12:09.079512: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:12:09.080813: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:12:09.104799: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:12:09.105162: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:12:09.488605: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:12:29] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:13:00.093185: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:13:00.094802: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:13:00.121018: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:13:00.121594: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:13:00.522975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:13:19] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:13:50.987899: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:13:50.989216: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:13:51.012890: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:13:51.013253: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:13:51.396925: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:14:10] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:14:41.790356: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:14:41.791823: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:14:41.816468: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:14:41.816817: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:14:42.218700: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
image-grouping-service  | Recluster flag set. This will affect the next recognition run.
image-grouping-service  | [ERROR] Failed to check Persons table: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service  | Persons table entries found: False. Setting recluster=False
image-grouping-service  | [AUTO] Pipeline execution started...
image-grouping-service  |
image-grouping-service  | [2025-09-01 10:15:01] Running full pipeline...
image-grouping-service  | [01] Detecting faces...
image-grouping-service  | [02] Running recognition pipeline...
image-grouping-service  | [Step 1:] Generating embeddings for missing faces...
image-grouping-service  | Traceback (most recent call last):
image-grouping-service  |   File "main.py", line 88, in <module>
image-grouping-service  |     main()
image-grouping-service  |   File "main.py", line 83, in main
image-grouping-service  |     automated_pipeline(interval_minutes=3, recluster=recluster_needed, dry_run=args.dry_run)
image-grouping-service  |   File "main.py", line 43, in automated_pipeline
image-grouping-service  |     full_pipeline_once(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "main.py", line 34, in full_pipeline_once
image-grouping-service  |     recognize_persons_main(recluster=recluster, dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 420, in main
image-grouping-service  |     process_missing_embeddings(dry_run=dry_run)
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 313, in process_missing_embeddings
image-grouping-service  |     rows = get_faces_with_bboxes()
image-grouping-service  |   File "/app/services/image_grouping/person_recognition/recognize_persons.py", line 33, in get_faces_with_bboxes
image-grouping-service  |     conn = pyodbc.connect(conn_str)
image-grouping-service  | pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
image-grouping-service exited with code 0
image-grouping-service  | 2025-09-01 10:15:32.883693: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
image-grouping-service  | 2025-09-01 10:15:32.885261: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:15:32.910926: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
image-grouping-service  | 2025-09-01 10:15:32.911329: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
image-grouping-service  | To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
image-grouping-service  | 2025-09-01 10:15:33.326418: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container image-grouping-service  Stopped                                                                                                   2.2s
^C
anumsaeed@DESKTOP-M2SFVT4:/mnt/c/Users/ADMIN/deepframe-backend/services/image_grouping$










anumsaeed@DESKTOP-M2SFVT4:~$ sudo docker ps
[sudo] password for anumsaeed:
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                             PORTS     NAMES
02f53b74fb26   image_grouping-image_grouping   "docker-entrypoint.sh"   5 minutes ago   Up 11 seconds (health: starting)             image-grouping-service
anumsaeed@DESKTOP-M2SFVT4:~$ sudo docker compose up -d sqlserver
no configuration file provided: not found
anumsaeed@DESKTOP-M2SFVT4:~$







Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

Loading personal and system profiles took 2132ms.
(base) PS C:\Users\ADMIN> docker imags
docker: unknown command: docker imags

Run 'docker --help' for more information
(base) PS C:\Users\ADMIN> docker images
REPOSITORY                                   TAG       IMAGE ID       CREATED          SIZE
image_grouping-image_grouping                latest    b89879bebe14   18 minutes ago   5.32GB
ghcr.io/immich-app/immich-server             release   e517f8064570   4 weeks ago      2.61GB
immich-machine-learning-dev                  latest    c8599d9896d5   4 weeks ago      1.37GB
immich-server-dev                            latest    62c4f9bbd971   4 weeks ago      4.09GB
immich-web-dev                               latest    39d6c311fe90   4 weeks ago      1.13GB
docker/welcome-to-docker                     latest    c4d56c24da4f   4 weeks ago      22.2MB
ghcr.io/immich-app/postgres                  <none>    32324a2f41df   5 weeks ago      987MB
ghcr.io/immich-app/immich-machine-learning   release   ef517c041fa4   6 weeks ago      1.37GB
valkey/valkey                                <none>    facc1d2c3462   7 weeks ago      167MB
(base) PS C:\Users\ADMIN> docker save -o deepframe.tar image_grouping-image_grouping
(base) PS C:\Users\ADMIN> sudo docker exec -it image-grouping-service bash
(base) PS C:\Users\ADMIN





# ********************************************************************
--CREATE DATABASE FaceRecognitionSystem;
--GO

USE FaceRecognitionSystem;
GO

-- dbo.MediaFile
CREATE TABLE dbo.MediaFile (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FilePath NVARCHAR(500) NOT NULL,
    FileName NVARCHAR(255) NOT NULL,
    Extensions NVARCHAR(10) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ModifiedAt DATETIME2 NULL
);
GO

-- dbo.MediaItems
CREATE TABLE dbo.MediaItems (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MediaFileId INT NOT NULL,
    FileName NVARCHAR(255) NOT NULL,
    IsFacesExtracted BIT NOT NULL DEFAULT 0,
    FacesExtractedOn DATETIME2 NULL,
    CONSTRAINT FK_MediaItems_MediaFile FOREIGN KEY (MediaFileId) REFERENCES dbo.MediaFile(Id)
);
GO

-- dbo.Persons
CREATE TABLE dbo.Persons (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PortraitFaceId INT NULL,
    Name NVARCHAR(255),
    Rank NVARCHAR(50) NULL,
    Appointment NVARCHAR(100) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ModifiedAt DATETIME2 NULL
);
GO

-- dbo.Faces
CREATE TABLE dbo.Faces (
    Id INT IDENTITY(1,1) PRIMARY KEY, 
    MediaItemId INT NOT NULL,
    PersonId INT NULL,
    BoundingBox NVARCHAR(255) NULL,
    Embedding VARBINARY(MAX) NULL, 
    FrameNumber INT NULL,
    Name NVARCHAR(255),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ModifiedAt DATETIME2 NULL,
    CONSTRAINT FK_Faces_MediaItem FOREIGN KEY (MediaItemId) REFERENCES dbo.MediaItems(Id),
    CONSTRAINT FK_Faces_Person FOREIGN KEY (PersonId) REFERENCES dbo.Persons(Id)
);
GO

ALTER TABLE dbo.Persons
ADD CONSTRAINT FK_Persons_Face FOREIGN KEY (PortraitFaceId) REFERENCES dbo.Faces(Id);
GO

# ********************************************************************
USE FaceRecognitionSystem;
GO

-- Insert into dbo.MediaFile with FULL file paths
INSERT INTO dbo.MediaFile (FilePath, FileName, Extensions, CreatedAt, ModifiedAt)
VALUES
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'conference.jpg', '.jpg', '2025-08-06 11:59:00', '2025-08-06 11:59:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'conference_hamid.png', '.png', '2025-08-15 09:53:00', '2025-08-15 09:53:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'family.jpg', '.jpg', '2025-08-11 10:12:00', '2025-08-11 10:12:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'female_anchor.jpg', '.jpg', '2025-08-05 13:15:00', '2025-08-05 13:15:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'GroupM.jpg', '.jpg', '2025-08-08 08:42:00', '2025-08-08 08:42:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'Hamid_Mir_at_Studio.png', '.png', '2025-08-15 09:55:00', '2025-08-15 09:55:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'image-talk-show.jpg', '.jpg', '2025-08-15 09:54:00', '2025-08-15 09:54:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'image.jpg', '.jpg', '2025-08-15 09:53:00', '2025-08-15 09:53:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'image_1.jpg', '.jpg', '2025-08-13 09:21:00', '2025-08-13 09:21:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'interview.jpg', '.jpg', '2025-08-06 11:59:00', '2025-08-06 11:59:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'interview_anchor.jpg', '.jpg', '2025-08-15 09:54:00', '2025-08-15 09:54:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'Jenny.jpg', '.jpg', '2025-08-11 09:33:00', '2025-08-11 09:33:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'kid.jpg', '.jpg', '2025-08-12 12:00:00', '2025-08-12 12:00:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'lunch.jpg', '.jpg', '2025-08-12 11:55:00', '2025-08-12 11:55:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'marriage.jpg', '.jpg', '2025-08-11 09:12:00', '2025-08-11 09:12:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'memory.jpg', '.jpg', '2025-08-12 12:00:00', '2025-08-12 12:00:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'news.jpg', '.jpg', '2025-08-06 11:59:00', '2025-08-06 11:59:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'political.jpg', '.jpg', '2025-08-07 14:30:00', '2025-08-07 14:30:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'political_leader.png', '.png', '2025-08-15 11:32:00', '2025-08-15 11:32:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'protest.jpg', '.jpg', '2025-08-13 09:20:00', '2025-08-13 09:20:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'radio_pakisatn.jpg', '.jpg', '2025-08-07 15:08:00', '2025-08-07 15:08:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'random.jpg', '.jpg', '2025-08-15 09:54:00', '2025-08-15 09:54:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'smiles.jpg', '.jpg', '2025-08-11 09:55:00', '2025-08-11 09:55:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'strike.jpg', '.jpg', '2025-08-13 09:20:00', '2025-08-13 09:20:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'talk.jpg', '.jpg', '2025-08-13 09:20:00', '2025-08-13 09:20:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'trip.jpg', '.jpg', '2025-08-12 10:33:00', '2025-08-12 10:33:00'),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'wedding.jpg', '.jpg', '2025-08-12 10:25:00', '2025-08-12 10:25:00')
;

-- Now insert into MediaItems only for these new rows
INSERT INTO dbo.MediaItems (MediaFileId, FileName, IsFacesExtracted, FacesExtractedOn)
SELECT Id, FileName, 0, NULL
FROM dbo.MediaFile
WHERE FileName IN (
    'conference.jpg','conference_hamid.png','family.jpg','female_anchor.jpg','GroupM.jpg',
    'Hamid_Mir_at_Studio.png','image-talk-show.jpg','image.jpg','image_1.jpg','interview.jpg',
    'interview_anchor.jpg','Jenny.jpg','kid.jpg','lunch.jpg','marriage.jpg','memory.jpg',
    'news.jpg','political.jpg','political_leader.png','protest.jpg','radio_pakisatn.jpg',
    'random.jpg','smiles.jpg','strike.jpg','talk.jpg','trip.jpg','wedding.jpg'
);

USE FaceRecognitionSystem;
GO

-- 1. Insert into dbo.MediaFile
INSERT INTO dbo.MediaFile (FilePath, FileName, Extensions, CreatedAt, ModifiedAt)
VALUES
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'hamidMir.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'imran_khan_img.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'Shaista-Lodhi.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'shaista.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'IK.png', '.png', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'lodhi.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'SLK.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'IK_image.png', '.png', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'Imran_Khan.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'Imran-Khan.jpg', '.jpg', GETDATE(), GETDATE()),
('C:/Users/ADMIN/Downloads/FRS_Project/services/image_grouping/image_face_detection/Images', 'Hamid_MIR.jpg', '.jpg', GETDATE(), GETDATE());

-- 2. Insert into dbo.MediaItems for each new MediaFile row
INSERT INTO dbo.MediaItems (MediaFileId, FileName, IsFacesExtracted, FacesExtractedOn)
SELECT Id, FileName, 0, NULL
FROM dbo.MediaFile
WHERE FileName IN ('hamidMir.jpg','imran_khan_img.jpg','Shaista-Lodhi.jpg','shaista.jpg','IK.png','lodhi.jpg','SLK.jpg','IK_image.png','Imran_Khan.jpg','Imran-Khan.jpg','Hamid_MIR.jpg');

USE FaceRecognitionSystem;

-- Insert into MediaFile
INSERT INTO dbo.MediaFile (FilePath, FileName, Extensions, CreatedAt, ModifiedAt)
VALUES
('C:/Users/ADMIN/deepframe-backend/services/image_grouping/image_face_detection/Images', 'image-political-conference.jpg', '.jpg', GETDATE(), GETDATE());

-- Insert into MediaItems for the 3 new files only
INSERT INTO dbo.MediaItems (MediaFileId, FileName, IsFacesExtracted, FacesExtractedOn)
SELECT mf.Id, mf.FileName, 0, NULL
FROM dbo.MediaFile mf
WHERE mf.FileName IN ('image-political-conference.jpg');


#****************************************************************************************
USE FaceRecognitionSystem;

SELECT * FROM dbo.MediaFile;
SELECT * FROM dbo.MediaItems;
SELECT * FROM dbo.Faces;
SELECT * FROM dbo.Persons;



#****************************************************************************************
USE FaceRecognitionSystem;

SELECT 
    F.Id AS FaceId,
    F.PersonId,
    MF.FilePath,
    MF.FileName,
    F.BoundingBox
FROM dbo.Faces F
JOIN dbo.MediaItems MI ON F.MediaItemId = MI.Id
JOIN dbo.MediaFile MF ON MI.MediaFileId = MF.Id
LEFT JOIN dbo.Persons P ON F.PersonId = P.Id
WHERE F.PersonId IS NOT NULL
ORDER BY F.PersonId, F.Id;


#****************************************************************************************
USE FaceRecognitionSystem;
GO

-- Drop foreign key constraints
ALTER TABLE dbo.Faces DROP CONSTRAINT FK_Faces_MediaItem;
ALTER TABLE dbo.Faces DROP CONSTRAINT FK_Faces_Person;
ALTER TABLE dbo.Persons DROP CONSTRAINT FK_Persons_Face;
ALTER TABLE dbo.MediaItems DROP CONSTRAINT FK_MediaItems_MediaFile;
GO

-- Drop tables in order
DROP TABLE IF EXISTS dbo.Faces;
DROP TABLE IF EXISTS dbo.Persons;
DROP TABLE IF EXISTS dbo.MediaItems;
DROP TABLE IF EXISTS dbo.MediaFile;
GO



#*